name: gnome-sudoku
version: 3.22.2
summary: Test your logic skills in this number grid puzzle
description: |
  Play the popular Japanese logic game. GNOME Sudoku is a must-install for
  Sudoku lovers, with a simple, unobtrusive interface that makes playing
  Sudoku fun for players of any skill level.

  Each game is assigned a difficulty similar to those given by newspapers
  and websites, so your game will be as easy or as difficult as you want it
  to be.

  If you like to play on paper, you can print games out. You can choose how
  many games you want to print per page and what difficulty of games you
  want to print: as a result, GNOME Sudoku can act a renewable Sudoku book
  for you.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict

plugs:
    gnome-3-24-platform:
      interface: content
      target: $SNAP/gnome-platform
      default-provider: gnome-3-24:gnome-3-24-platform

slots:
  # for GtkApplication registration
  gnome-sudoku:
    interface: dbus
    bus: session
    name: org.gnome.sudoku

apps:
  gnome-sudoku:
    command: desktop-launch gnome-sudoku
    plugs:
      - network
      - x11
      - home
      - gsettings
      - unity7
    desktop: usr/share/applications/gnome-sudoku.desktop
    environment:
      GSETTINGS_SCHEMA_DIR: $SNAP/share/glib-2.0/schemas
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/lib/gnome-sudoku

parts:
  desktop-gnome-platform:
    source-subdir: gtk
    plugin: make
    make-parameters: ["FLAVOR=gtk3"]
    build-packages:
      - libgtk-3-dev
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-branch: master
    install: mkdir -p $SNAPCRAFT_PART_INSTALL/gnome-platform

  gnome-sudoku:
    source: https://git.gnome.org/browse/gnome-sudoku
    source-type: git
    #source-branch: master
    source-tag: 3.24.0
    plugin: autotools
    # workaround the issue described in https://launchpad.net/bugs/1583250
    configflags: [--prefix=/snap/gnome-sudoku/current/usr]
    organize:
      snap/gnome-sudoku/current/usr: usr
    prepare:
      sed -i.bak -e 's|=gnome-sudoku$|=${SNAP}/meta/gui/gnome-sudoku.png|g' data/gnome-sudoku.desktop.in
    install: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/meta/gui/
      cp ../src/data/icons/hicolor/48x48/gnome-sudoku.png $SNAPCRAFT_PART_INSTALL/meta/gui/
      cp data/gnome-sudoku.desktop $SNAPCRAFT_PART_INSTALL/meta/gui/
    build-packages:
      - desktop-file-utils
      - gettext
      - gnome-common
      - appstream-util
      - gnome-pkg-tools
      - intltool
      - libgee-0.8-dev
      - libjson-glib-dev
      - libglib2.0-dev
      - libgtk-3-dev
      - libqqwing-dev
      - valac
      - yelp-tools


  # workaround snapcraft trying to outsmart us by copying ldd listed libraries
  workaround:
    plugin: nil
    prime:
      - "-*"
